// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParkLookup.Models;

namespace ParkLookup.Migrations
{
    [DbContext(typeof(ParkLookupContext))]
    partial class ParkLookupContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("ParkLookup.Models.Park", b =>
                {
                    b.Property<int>("ParkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Coordinates")
                        .HasColumnType("int");

                    b.Property<int>("Established")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Province")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("ParkId");

                    b.ToTable("Parks");

                    b.HasData(
                        new
                        {
                            ParkId = 1,
                            Coordinates = 0,
                            Established = 2020,
                            Name = "Himalaya National Park",
                            Province = "GB"
                        },
                        new
                        {
                            ParkId = 2,
                            Coordinates = 0,
                            Established = 2012,
                            Name = "Hundrap-Shandur National Park",
                            Province = "GB"
                        },
                        new
                        {
                            ParkId = 3,
                            Coordinates = 0,
                            Established = 2010,
                            Name = "Nanga-Parbat National Park",
                            Province = "GB"
                        },
                        new
                        {
                            ParkId = 4,
                            Coordinates = 0,
                            Established = 1993,
                            Name = "Broghil Valley",
                            Province = "KP"
                        },
                        new
                        {
                            ParkId = 5,
                            Coordinates = 0,
                            Established = 1987,
                            Name = "Central Karakoram",
                            Province = "GB"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
